name: manage-azure-policy-d4c5d399
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_a_Flow_Log_resource_with_Traffic_Analytics_for_an_NSG_13a0c538-a55c-4b56-8664-35641dc68101/**'
#      - .github/workflows/manage-azure-policy-d4c5d399.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d4c5d399}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_a_Flow_Log_resource_with_Traffic_Analytics_for_an_NSG_13a0c538-a55c-4b56-8664-35641dc68101/**
